import json
import logging
import re
from typing import List, Literal
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field, ValidationError
from app.services.ai.factory import get_ai_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ai", tags=["AI"])

def clean_json_response(raw_text: str) -> str:
    """Removes thinking tags or markdown code fences from AI model output."""
    cleaned = re.sub(r'<think>.*?</think>', '', raw_text, flags=re.DOTALL)
    cleaned = re.sub(r'```(?:json)?\s*(.*?)\s*```', r'\1', cleaned, flags=re.DOTALL)
    return cleaned.strip()

class AITestRequest(BaseModel):
    prompt: str = Field(..., description="Prompt text to send to AI model", example="Generate 3 viva questions about TCP.")

class AITestResponse(BaseModel):
    response: str = Field(..., description="Response generated by the AI model")

class VivaQuestionItem(BaseModel):
    question: str = Field(..., description="The viva question text")
    difficulty: str = Field(..., description="Difficulty level of question: easy, medium, or hard")
    topic: str = Field(..., description="Topic of the question")

class VivaQuestionRequest(BaseModel):
    topic: str = Field(..., min_length=1, description="Topic for viva questions", example="TCP")
    num_questions: int = Field(..., ge=1, le=10, description="Number of questions to generate (1-10)", example=5)
    difficulty: Literal["easy", "medium", "hard", "mixed"] = Field("mixed", description="Target difficulty level", example="mixed")

class VivaQuestionResponse(BaseModel):
    questions: List[VivaQuestionItem] = Field(..., description="List of generated viva questions")

class VivaEvaluateRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The viva question asked", example="How does TCP provide reliable data delivery?")
    answer: str = Field(..., min_length=1, description="The student's oral answer draft", example="TCP uses acknowledgements and retransmissions.")
    topic: str = Field("General", description="Topic of the question", example="TCP")
    difficulty: str = Field("medium", description="Difficulty level", example="medium")

class VivaEvaluateResponse(BaseModel):
    score: int = Field(..., ge=0, le=10, description="Evaluation score from 0 to 10")
    correctness: str = Field(..., description="One of: Incorrect, Partially Correct, Mostly Correct, Correct")
    feedback: str = Field(..., description="Concise educational feedback explaining strengths and missing details")
    ideal_answer: str = Field(..., description="Concise model answer appropriate for a university viva")
    follow_up_question: str = Field(..., description="A relevant follow-up viva question")

@router.post("/test", response_model=AITestResponse)
async def test_ai_connection(request: AITestRequest):
    """Test connection to local or remote AI server and generation."""
    ai_service = get_ai_service()
    response_text = await ai_service.generate_response(request.prompt)
    return AITestResponse(response=response_text)

@router.post("/questions", response_model=VivaQuestionResponse)
async def generate_viva_questions(request: VivaQuestionRequest):
    """Generate structured viva questions for university Computer Engineering students using AI service."""
    prompt = f"""You are a Computer Science and Engineering university professor conducting an oral viva exam for an undergraduate Computer Engineering student.
Generate exactly {request.num_questions} conceptual viva questions on the topic "{request.topic}".
Target difficulty level: {request.difficulty}.

Requirements:
- Questions must test conceptual understanding, architectural reasoning, and practical trade-offs, not just rote definitions.
- For difficulty: if requested difficulty is "mixed", distribute difficulty across "easy", "medium", and "hard". Otherwise set difficulty for all questions to "{request.difficulty}".
- Always set the "topic" field of every question object to "{request.topic}".

Output JSON format strictly matching this schema:
{{
  "questions": [
    {{
      "question": "question text",
      "difficulty": "easy|medium|hard",
      "topic": "{request.topic}"
    }}
  ]
}}
"""

    ai_service = get_ai_service()
    raw_response = await ai_service.generate_response(prompt, format="json")
    cleaned_text = clean_json_response(raw_response)

    try:
        data = json.loads(cleaned_text)
    except json.JSONDecodeError as err:
        logger.error(f"Failed to parse JSON from AI model response: {err}. Raw response: {raw_response}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service returned invalid JSON response format."
        )

    try:
        validated_response = VivaQuestionResponse.model_validate(data)
        return validated_response
    except ValidationError as err:
        logger.error(f"AI response failed schema validation: {err}. Parsed data: {data}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"AI service returned invalid structured data layout."
        )

@router.post("/evaluate", response_model=VivaEvaluateResponse)
async def evaluate_viva_answer(request: VivaEvaluateRequest):
    """Evaluate a student's oral answer to a viva question using Ollama AI."""
    prompt = f"""You are a Computer Science university professor evaluating a student's answer in an oral viva exam.

Question Asked: "{request.question}"
Topic: "{request.topic}" (Difficulty: {request.difficulty})
Student's Answer: "{request.answer}"

Evaluation Instructions:
1. Evaluate the student's conceptual understanding based on the question asked. Do NOT rely merely on keyword matching.
2. Assign an integer score from 0 to 10 (0 = completely wrong/irrelevant, 10 = perfect comprehensive answer).
3. Set correctness to exactly one of: "Incorrect", "Partially Correct", "Mostly Correct", or "Correct".
4. Provide concise, constructive feedback explaining what the student got right and what key concepts were missing or inaccurate.
5. Provide a concise ideal viva answer appropriate for an undergraduate university exam.
6. Formulate one relevant, insightful follow-up viva question based on the topic.
7. Output NO chain-of-thought or reasoning text. Return ONLY a valid JSON object matching this schema:
{{
  "score": <integer from 0 to 10>,
  "correctness": "<Incorrect | Partially Correct | Mostly Correct | Correct>",
  "feedback": "<concise feedback about the student's actual answer>",
  "ideal_answer": "<concise ideal answer to the actual question>",
  "follow_up_question": "<relevant follow-up question about the actual question/topic>"
}}

IMPORTANT:
- Evaluate ONLY the current Question Asked and Student's Answer provided above.
- Every field must be specific to the current question and current student answer.
- Do NOT copy, reuse, or imitate evaluation content from this prompt.
- Do NOT assume the question is about TCP unless the current question actually concerns TCP.
- The ideal answer must directly answer the current question.
- The follow-up question must be relevant to the current question and topic.
"""

    ai_service = get_ai_service()
    raw_response = await ai_service.generate_response(prompt, format="json")
    cleaned_text = clean_json_response(raw_response)

    try:
        data = json.loads(cleaned_text)
    except json.JSONDecodeError as err:
        logger.error(f"Failed to parse JSON evaluation from AI model: {err}. Raw response: {raw_response}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service returned invalid JSON evaluation format."
        )

    try:
        validated_response = VivaEvaluateResponse.model_validate(data)
        return validated_response
    except ValidationError as err:
        logger.error(f"AI evaluation failed schema validation: {err}. Parsed data: {data}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"AI service returned invalid structured evaluation layout."
        )

# MVP Context Limit: Truncate material to 12,000 characters to fit LLM context window without RAG/chunking
MAX_MATERIAL_CHARS = 12000

class VivaQuestionFromMaterialRequest(BaseModel):
    material: str = Field(..., min_length=1, description="Extracted study material text", example="Computer Networks lecture notes...")
    topic: str = Field("General", description="Topic/Subject name", example="Computer Networks")
    num_questions: int = Field(5, ge=1, le=10, description="Number of questions (1-10)", example=5)
    difficulty: Literal["easy", "medium", "hard", "mixed"] = Field("mixed", description="Target difficulty level", example="mixed")

@router.post("/questions/from-material", response_model=VivaQuestionResponse)
async def generate_viva_questions_from_material(request: VivaQuestionFromMaterialRequest):
    """Generate structured viva questions based primarily on uploaded study material text using AI service."""
    material_text = request.material
    if len(material_text) > MAX_MATERIAL_CHARS:
        logger.info(f"Truncating study material from {len(material_text)} to {MAX_MATERIAL_CHARS} characters for LLM context window.")
        material_text = material_text[:MAX_MATERIAL_CHARS]

    prompt = f"""You are a Computer Science and Engineering university professor conducting an oral viva exam for an undergraduate Computer Engineering student.
Below is the student's actual study material on the topic "{request.topic}":

--- STUDY MATERIAL BEGIN ---
{material_text}
--- STUDY MATERIAL END ---

Generation Instructions:
1. Generate exactly {request.num_questions} conceptual viva questions based PRIMARILY on the supplied study material above.
2. Do NOT invent topics or concepts that are completely unrelated to the supplied study material.
3. Test conceptual understanding, problem-solving, architectural trade-offs, and reasoning based on the material, rather than simply copying sentences or asking for verbatim definitions.
4. Target difficulty level: {request.difficulty}. If requested difficulty is "mixed", distribute difficulty across "easy", "medium", and "hard". Otherwise set difficulty for all questions to "{request.difficulty}".
5. Always set the "topic" field of every question object to "{request.topic}".
6. Do NOT return answers or reasoning. Return ONLY a valid JSON object matching this exact schema:

{{
  "questions": [
    {{
      "question": "question text based on study material",
      "difficulty": "easy|medium|hard",
      "topic": "{request.topic}"
    }}
  ]
}}
"""

    ai_service = get_ai_service()
    raw_response = await ai_service.generate_response(prompt, format="json")
    cleaned_text = clean_json_response(raw_response)

    try:
        data = json.loads(cleaned_text)
    except json.JSONDecodeError as err:
        logger.error(f"Failed to parse JSON from AI model response: {err}. Raw response: {raw_response}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service returned invalid JSON response format."
        )

    try:
        validated_response = VivaQuestionResponse.model_validate(data)
        return validated_response
    except ValidationError as err:
        logger.error(f"AI response failed schema validation: {err}. Parsed data: {data}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"AI service returned invalid structured data layout."
        )

